---
name: on_file_hello
pack: boston
enabled: true
trigger:
    type: linux.file_watch.line
    parameters:
      file_path: /tmp/zoo

criteria: {}

action:
  ref: boston.hello
  parameters:
    name:  "{{ trigger.line }}"

